### ISSUE TITLE
[Bug]: Braze 35.0.0 will not work with androidx.compose:compose-bom:2025.04.01

### ISSUE THREAD

**Issue by renebaeu** [braze-inc/braze-android-sdk#67]
### Braze Android SDK Version

35.0.0

### Steps To Reproduce

Create an App with:
SDK Version: 35.0.0
androidx.compose:compose-bom:2025.04.01 (works with 2025.04.00)

Create a InboxContent with ContentCardsList like this:

 Box(modifier = modifier) {
        ContentCardsList(
            cardUpdateHandler = { cards ->
                cards
                    .filter { card -> card.extras[FEED_TYPE_KEY] == FEED_TYPE_PUSH_VALUE }
                    .sortedWith { cardA, cardB ->
                        if (cardA.isPinned && !cardB.isPinned) {
                            return@sortedWith -1
                        }
                        if (!cardA.isPinned && cardB.isPinned) {
                            return@sortedWith 1
                        }
                        if (cardA.updated > cardB.updated) {
                            return@sortedWith -1
                        }
                        if (cardA.updated < cardB.updated) {
                            return@sortedWith 1
                        }
                        0
                    }
            },
...

Create a content card in dashboard and send to device.

### Expected Behavior

Show the content card

### Actual Incorrect Behavior

Crash with exception:

java.lang.NoSuchMethodError: No static method animateItemPlacement$default(Landroidx/compose/foundation/lazy/LazyItemScope;Landroidx/compose/ui/Modifier;Landroidx/compose/animation/core/FiniteAnimationSpec;ILjava/lang/Object;)Landroidx/compose/ui/Modifier; in class Landroidx/compose/foundation/lazy/LazyItemScope; or its super classes (declaration of 'androidx.compose.foundation.lazy.LazyItemScope' appears in ...
                                                                                                    	at com.braze.jetpackcompose.contentcards.ContentCardsListKt$ContentCardsList$lambda$59$lambda$58$lambda$57$$inlined$items$default$4.invoke(LazyDsl.kt:475)
                                                                                                    	at com.braze.jetpackcompose.contentcards.ContentCardsListKt$ContentCardsList$lambda$59$lambda$58$lambda$57$$inlined$items$default$4.invoke(LazyDsl.kt:148)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:142)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderImpl$Item$1.invoke(LazyListItemProvider.kt:84)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderImpl$Item$1.invoke(LazyListItemProvider.kt:82)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:384)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutPinnableItemKt.LazyLayoutPinnableItem(LazyLayoutPinnableItem.kt:56)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.Item(LazyListItemProvider.kt:82)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:130)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:129)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:384)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:79)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(LazySaveableStateHolder.kt:76)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:129)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.access$SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:1)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:97)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(LazyLayoutItemContentFactory.kt:87)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)

### Verbose Logs

```shell

```

**Comment by chshapiro** [comment]
Hi @renebaeu,

We are looking into this and will update here as soon as we have more information.

Thanks!

**Comment by barry-irvine** [comment]
`animateItemPlacement` was deprecated a while back. You should have been using `animateItem`...

**Comment by chshapiro** [comment]
Hi all,
There will be a fix coming for this in an upcoming release.

**Comment by barry-irvine** [comment]
Any idea when we can expect the release?

**Comment by bryanlogan** [comment]
This is in the 36.0.0 we just released.
